apiVersion: apps/v1
kind: Deployment
metadata: 
  name: crawler
spec:
  template:
    spec:
      containers:
      - name: fast-crawler
        image: omarmoreno/crawler:0.2.1
        imagePullPolicy: Always
        volumeMounts:
          - name: config-path
            mountPath: /opt/config
            subPath: workarea/software/crawler/fast_crawler_config
          - name: sdf-group
            mountPath: /sdf/group/supercdms/data
            subPath: data
          - name: sdf-data
            mountPath: /sdf/data/supercdms/data
            subPath: data
      volumes:
        - name: config-path
          persistentVolumeClaim:
            claimName: sdf-data-supercdms-config-ro
        - name: sdf-group
          persistentVolumeClaim:
            claimName: sdf-group-supercdms-ro
        - name: sdf-data
          persistentVolumeClaim:
            claimName: sdf-data-supercdms-ro

