apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mini-crawler

namePrefix: mini-

commonLabels:
  app: mini-crawler

resources:
- ../../base

patches: 
- path: mini-crawler.yaml
